# Generated by Django 5.0.6 on 2025-04-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chatmessage_buyer_alter_chatmessage_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('cash', 'Cash on Delivery')], default='cash', max_length=20),
        ),
    ]
