# Generated by Django 5.0.6 on 2025-04-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
