# Generated by Django 5.2.6 on 2026-04-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')]),
        ),
    ]
