# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

class TestAddToCart():
    """Test suite for RoorReach add to cart and checkout functionality"""
    
    def setup_method(self, method):
        """Set up test environment before each test method"""
        chrome_options = Options()
        chrome_options.add_argument('--start-maximized')
        service = Service('chromedriver.exe')
        self.driver = webdriver.Chrome(service=service, options=chrome_options)
        self.wait = WebDriverWait(self.driver, 10)
        self.vars = {}

    def teardown_method(self, method):
        """Clean up after each test method"""
        if self.driver:
            self.driver.quit()

    def test_add_to_cart_and_checkout(self):
        """Test adding product to cart and completing checkout process"""
        try:
            # Navigate to login page first
            self.driver.get("http://127.0.0.1:8000/login/")
            
            # Login process
            username_field = self.wait.until(EC.presence_of_element_located((By.ID, "username")))
            username_field.send_keys("BBuyer")
            
            password_field = self.wait.until(EC.presence_of_element_located((By.ID, "password")))
            password_field.click()
            password_field.send_keys("Test@1234")
            
            # Click login button
            login_button = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn:nth-child(4)")))
            login_button.click()
            
            # Wait for login redirect
            self.wait.until(EC.url_changes("http://127.0.0.1:8000/login/"))
            
            # Find and click Add to Cart button
            add_to_cart_button = self.wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "Add to Cart")))
            add_to_cart_button.click()
            
            # Wait and click Proceed to Checkout
            checkout_button = self.wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "Proceed to Checkout")))
            checkout_button.click()
            
            # Fill checkout form
            self.wait.until(EC.presence_of_element_located((By.ID, "full_name"))).send_keys("Akhi")
            self.wait.until(EC.presence_of_element_located((By.ID, "phone"))).send_keys("01757499561")
            self.wait.until(EC.presence_of_element_located((By.ID, "email"))).send_keys("afrin@1234gmail.com")
            self.wait.until(EC.presence_of_element_located((By.ID, "shipping_address"))).send_keys("df")
            
            # Submit order
            place_order_button = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".place-order-btn")))
            place_order_button.click()
            
            # Verify order placement
            time.sleep(2)  # Wait for order processing
            # Add verification for successful order placement
            success_message = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success")))
            assert "order" in success_message.text.lower(), "Order placement failed"
            
            # Take screenshot of successful order
            self.driver.save_screenshot("order_success.png")
            print("✅ Add to cart and checkout test completed successfully!")
            
        except Exception as e:
            # Take screenshot of failure
            self.driver.save_screenshot("order_failure.png")
            print(f"❌ Test failed: {str(e)}")
            raise e
            
        finally:
            try:
                # Perform cleanup actions
                print("🧹 Cleaning up test session...")
                
                # Clear any remaining cart items (optional)
                self.driver.get("http://127.0.0.1:8000/cart/")
                time.sleep(1)
                
                # Log out
                print("👋 Logging out...")
                self.driver.get("http://127.0.0.1:8000/logout/")
                time.sleep(1)
                
                # Close browser properly
                print("🏁 Closing browser session...")
                self.driver.close()
                self.driver.quit()
                print("✨ Test cleanup completed successfully!")
                
            except Exception as cleanup_error:
                print(f"⚠️ Warning: Cleanup encountered an error: {str(cleanup_error)}")
                # Make sure to quit the driver even if cleanup fails
                if self.driver:
                    self.driver.quit()

