# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

class TestSignup():
    """Test suite for RoorReach signup functionality"""
    
    def setup_method(self, method):
        """Set up test environment before each test method"""
        chrome_options = Options()
        chrome_options.add_argument('--start-maximized')
        service = Service('chromedriver.exe')
        self.driver = webdriver.Chrome(service=service, options=chrome_options)
        self.wait = WebDriverWait(self.driver, 10)
        self.vars = {}

    def teardown_method(self, method):
        """Clean up after each test method"""
        if self.driver:
            self.driver.quit()

    def test_signup(self):
        """Test user registration functionality"""
        try:
            # Navigate to register page
            self.driver.get("http://127.0.0.1:8000/register")
            
            # Fill in registration form
            self.wait.until(EC.presence_of_element_located((By.ID, "id_username"))).send_keys("Testt")
            self.wait.until(EC.presence_of_element_located((By.ID, "id_first_name"))).send_keys("t")
            self.wait.until(EC.presence_of_element_located((By.ID, "id_last_name"))).send_keys("t")
            self.wait.until(EC.presence_of_element_located((By.ID, "id_email"))).send_keys("Test@gmail.com")
            self.wait.until(EC.presence_of_element_located((By.ID, "id_phone"))).send_keys("01757499561")
            
            # Handle gender dropdown
            gender_dropdown = self.wait.until(EC.presence_of_element_located((By.ID, "id_gender")))
            gender_dropdown.click()
            gender_option = self.wait.until(EC.presence_of_element_located((By.XPATH, "//option[. = 'Female']")))
            gender_option.click()
            
            # Fill remaining fields
            self.wait.until(EC.presence_of_element_located((By.ID, "id_location"))).send_keys("Jessore")
            self.wait.until(EC.presence_of_element_located((By.ID, "id_address"))).send_keys("ddfdsf")
            self.wait.until(EC.presence_of_element_located((By.ID, "id_password1"))).send_keys("Test@1234")
            self.wait.until(EC.presence_of_element_located((By.ID, "id_password2"))).send_keys("Test@1234")
            
            # Submit registration form
            submit_button = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn:nth-child(12)")))
            submit_button.click()
            
            # Verify successful registration
            self.wait.until(EC.url_changes("http://127.0.0.1:8000/register"))
            current_url = self.driver.current_url
            assert "login" in current_url.lower(), "Registration failed - not redirected to login page"
            
            # Take screenshot of successful registration
            self.driver.save_screenshot("signup_success.png")
            
        except Exception as e:
            # Take screenshot of failure
            self.driver.save_screenshot("signup_failure.png")
            raise e
            
        finally:
            # Ensure browser closes properly
            print("Closing browser session...")
            self.driver.close()
            self.driver.quit()

